apiVersion: v1
kind: deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: rollingUpdate
    rollingUpdate:
      maxSurge: 1               # Combien de Pods en plus pendant l'update
      maxUnavailable: 0          # Combien de Pods peuvent être indisponibles
    progressDeadlineSeconds: 600  # Timeout pour détecter un rollout bloqué
    minReadySeconds: 10           # Attendre 10s après Ready avant de continuer
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: andylucas06/aether-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SECRET_KEY
          envFrom:
            - configMapRef:
                name: backend-config
