apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: dev
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak-container
          image: quay.io/keycloak/keycloak:24.0
          containers:
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_HOSTNAME
              value: auth.itdesk.example.com
            - name: KC_PROXY
              value: edge
          envFrom: #secret
            - secretRef:
                name: keycloak-secret
            - configMapRef:
                name: backend-config
          volumeMounts:
                - name: kc-test
                  mountPath: /var/lib/pgrs
      volumes:
        - name: kc-test
          hostPath:
            path: /var/log