image:
  repository: andylucas06/itdesk-backend
  pullPolicy: IfNotPresent
  tag: ""

labels:
  app: itdesk-backend

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

config: {}

ingress:
  enabled: false


resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

postgres:
  enabled: true
  image: {}
  service: {}
  persistence: {}