apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
stringData:
  DB_USERNAME: itdesk_prod
  DB_PASSWORD: prod_db_password_change_me
  JWT_SECRET: 70726f642d6a77742d7365637265742d6b65792d3235362d626974732d736563
