apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume
  namespace: dev
  labels:
    app: database-volume
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi