apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  DB_NAME: "itdesk"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"