apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  namespace: dev
  labels:
    name: frontend
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - image:  andylucas06/itdesk-frontend:14
        name: itdesk-frontend
        imagePullPolicy: IfNotPresent
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
          containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}