apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  namespace: dev
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec: 
      containers:
      - image:  andylucas06/itdesk-frontend:23
        name: itdesk-frontend
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          emptyDir: {}