apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-svc
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  {{- with .Values.service }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
 
