{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.name" . }}-cfg
  labels:
    {{- include "backend.selectorLabels" . | nindent 4 }}

{{- with .Values.config }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}