apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.name" . }}-secret
  labels:
    {{- include "backend.selectorLabels" . | nindent 4 }}
type: Opaque
data: 
  DB_USERNAME: aXR0aWNrZXQ=
  DB_PASSWORD: aXR0aWNrZXQ=