apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.name" . }}-secret
  labels:
    {{- include "backend.selectorLabels" . | nindent 4 }}
type: Opaque
data: 
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==