apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: "/l30UtJiK1QBbbF0Gke390ZS32XgtshvcO34TftZuTrklRuhpbS3a4pN+hrgJCPf"
  JWT_ACCESS_TOKEN_VALIDITY_SECONDS: "900"
  JWT_REFRESH_TOKEN_VALIDITY_SECONDS: "604800"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"