apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-svc
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    {{- with .Values.service }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
