apiVersion: v2
name: helm
description: A helm chart for It-Ticket
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
    