apiVersion: v2
name: helm
description: A helm chart for It-Ticket
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: keycloak
    version: 0.21.34
    repository: "oci://registry-1.docker.io/cloudpirates"
  # - name: postgres
  #   version: 0.20.4
  #   repository: "oci://registry-1.docker.io/cloudpirates"