frontend:
  replicaCount: 1
  image:
    repository: andylucas06/itdesk-frontend
    pullPolicy: IfNotPresent
    tag: ""

  ports:
    - name: http-port-frontend
      containerPort: 80
      protocol: TCP

  service:
    port: 8080
    targetPort: http-port-frontend
    protocol: TCP

  ingress:
    enabled: false
    tls: []

backend:
  replicaCount: 1

  image:
    repository: andylucas06/itdesk-backend
    pullPolicy: IfNotPresent
    tag: ""
  
  ports:
    - name:  http-port
      containerPort: 8080
      protocol: TCP
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: http-port

  config: {}
    
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: app.itticket.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: itticket-frontend-svc
              port:
                number: 8080
    - host: api.itticket.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: itticket-backend-svc
              port:
                number: 8080
    - host: auth.itticket.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: itticket-keycloak
              port:
                number: 8080
  # tls: 
  #   - secretName: chart-example-tls
  #     hosts:  
  #       - app.itticket.local
autoscaling:
  enabled: false
httpRoute:
  enabled: false 

resources:
  enabled: false
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumes: []

volumeMounts: []