frontend:
  replicaCount: 1
  image:
    repository: andylucas06/itdesk-frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  ports:
    - name: http-port
      containerPort: 80
      protocol: TCP
  service:
    - port: 8080
      targetPort: http-port
      protocol: TCP

backend:
  replicaCount: 1
  image:
    repository: andylucas06/itdesk-backend
    pullPolicy: IfNotPresent
    tag: "14"
  ports:
    - name:  http-port
      containerPort: 8080
      protocol: TCP
  service:
    - port: 8080
      targetPort: http-port
      protocol: TCP
      
  config:

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: app.itticket.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: itticket-frontend-svc
              port:
                number: 8080
    - host: api.itticket.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: itticket-backend-svc
              port:
                number: 8080
    - host: auth.itticket.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: itticket-keycloak
              port:
                number: 8080