name: CI
on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: checkout sc
        uses: actions/checkout@v4
        
      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: 20
          cache-dependency-path: frontend/package-lock.json

      - name: install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: lint
        working-directory: frontend
        run: npm run lint
        
      - name: test
        working-directory: frontend
        run: npm run test
        
      - name: build
        working-directory: frontend
        run: npm run build
